---
- name:  This playbook will install http stack
  hosts: test
  become: yes
  become_method: sudo
  tasks:
    - name: This module will install httpd
      yum:
       name: httpd
       state: latest
      tags:
        - install
 
    - name: Start httpd service 
      service:
       name: httpd
       state: started
       enabled: yes
      tags:
        - service
