---
- name:  This playbook will install http stack
  hosts: test
  vars:
    http_port: 80
  become: yes
  become_method: sudo
  tasks:
    - name: This module will install httpd {{http_port}}
      yum:
       name: httpd
       state: latest
      notify: "restart web services"
      tags:
        - install
 
  handlers:
    - name: restart web services
      service:
       name: httpd
       state: started
